version: '3.6'
services:
  web1:
    build: ./web/
    volumes:
      - ./web/:/web/
    working_dir: /web/
    command: npm run dev
    environment:
      - VIRTUAL_HOST=web1
      - VIRTUAL_PORT=3000
    container_name: web1
  web2:
    build: ./web/
    volumes:
      - ./web/:/web/
    working_dir: /web/
    command: npm run dev
    environment:
      - VIRTUAL_HOST=web2
      - VIRTUAL_PORT=3000
    container_name: web2
  api:
    build: ./api/
    volumes:
      - ./api/:/api/
    working_dir: /api/
    command: npm run dev
    container_name: api
    environment:
      - VIRTUAL_HOST=api
      - VIRTUAL_PORT=3000
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx